os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode9.3
env:
  - SWIFT_VERSION=4.1
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
  - swift build
  - swift test